### ISSUE TITLE
Miscall to file?

### ISSUE THREAD

**Issue by mattloose** [marcpaga/sturgeon#5]
https://github.com/marcpaga/sturgeon/blob/ed7905585d710faa17390ad859d72f11388e4820/sturgeon/callmapping.py#L275C40-L275C40

Should this not be probes_file instead of probes_df in the function call?

e.g 

probes_df = read_probes_file(probes_file)

**Comment by marcpaga** [comment]
You are completely right, I have pushed a fix for this.
