### ISSUE TITLE
onnxruntime==1.12.1

### ISSUE THREAD

**Issue by vzupan3** [marcpaga/sturgeon#7]
Hi,

during installation:
pip3 install . --no-cache-dir 
I get:
ERROR: No matching distribution found for onnxruntime==1.12.1.

Many thanks for the feedback!

**Comment by marcpaga** [comment]
Hi @vzupan3,

on a fresh linux python3.8 virtual environment I am able to install all dependencies. It is difficult to try to solve this without more information. 

You can also try to install another onnxruntime version (>1.12) since it will probably be compatible.

**Comment by vzupan3** [comment]
Thank you for quick feedback.

This is complete ERROR:
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.12.1 (from sturgeon) (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.12.1

I think the problem might be in my Python version which is  3.11.6

**Comment by vzupan3** [comment]
I did resolve the issue by setting Python version 3.8.0 for the sturgeon directory. Many thanks again and keep up the good work!
