### ISSUE TITLE
Version in __init__.py

### ISSUE THREAD

**Issue by jkuhl-uni** [marcpaga/sturgeon#8]
Hey there,
I don't watn to bother, I was just installing sturgeon on a cluster and during testing I saw, that the version number of version v0.4.3 is shown incorrectly as v0.4.2. This stems from the `__init__.py` l. 3, where I guess the version number wasn't bumped.
Just as a notice for you :)

Cheers,
Justus

**Comment by marcpaga** [comment]
Thanks! I bumped it now
