### ISSUE TITLE
Not enough values to unpack in live.py line 471

### ISSUE THREAD

**Issue by chinmaysharmacs10** [marcpaga/sturgeon#9]
In live.py the load model method does not return weight_matrix. However line 471 is expecting weight_matrix as a return parameter which means that line is expecting 6 return parameters instead of 5. This leads to an error. 

Moreover, weight_matrix is not being used later, so it seems to be a mistake. 

<img width="1036" alt="Screenshot 2024-02-09 at 10 24 39 AM" src="https://github.com/marcpaga/sturgeon/assets/35448762/5a98b004-066d-4876-8674-fc6f28eee7d8">

**Comment by marcpaga** [comment]
Thanks for the bug report, fixed in https://github.com/marcpaga/sturgeon/commit/49a7666dfd7e12f6a63d40a1f01a30fac64652f9.
